[package]
authors = ["Vivek Kushwaha <yoursvivek@gmail.com>"]
license = "MIT"
name = "imdb"
version = "0.0.1"
description = "imdb is a library to retrieve information from IMDb"
homepage = "https://github.com/yoursvivek/imdb"
repository = "https://github.com/yoursvivek/imdb"
readme = "README.md"
keywords = ["imdb", "scraping", "movies"]


[dependencies]
derive_builder = "0.5.0"
hyper = "0.11.6"
language-tags = "0.2.2"
log = "0.3.8"
reqwest = "0.8.0"
scraper = "0.4.0"
url = "1.6.0"

[dependencies.serde]
optional = true
version = "1.0"

[dependencies.serde_derive]
optional = true
version = "1.0"

[dev-dependencies]
glob = "0.2.11"
colored = "1.6.0"
env_logger = "0.4.3"
terminal_size = "0.1.7"

[features]
serde-impls = [
    "serde_derive",
    "serde",
]
